// resources/js/apps/campaign/components/Characters/CharacterOverview/CharacterOverview.tsx
import classNames from "classnames";
import { FC } from "react";
import { Link, Outlet, useLocation } from "react-router-dom";

const CharacterOverview: FC = () => {
  const location = useLocation()

  return <div id="characters">
    <h1>Characters</h1>
    <div className="uk-section uk-section-default uk-padding-remove-top">
      <ul className="uk-tab">
        <li className={classNames({
          'uk-active': [
            '/characters/players',
            '/characters'
          ].includes(location.pathname)
        })}>
          <Link to="players">Player Characters</Link>
        </li>
        <li className={classNames({ 'uk-active': location.pathname == '/characters/npcs' })}>
          <Link to="npcs">NPC's</Link>
        </li>
      </ul>
      <Outlet />
    </div>
  </div>
}

export default CharacterOverview

// resources/js/components/characters/character-overview.vue
<template>
    <div id="characters">
        <h1>Characters</h1>
        <div class="uk-section uk-section-default">
            <div class="uk-container padded">
                <ul class="uk-tab">
                    <li :class="{'uk-active': $route.name == 'player-characters'}">
                        <router-link :to="{name: 'player-characters'}">
                            Player Characters
                        </router-link>
                    </li>
                    <li :class="{'uk-active': $route.name == 'npcs'}">
                        <router-link :to="{name: 'npcs'}">
                            NPC's
                        </router-link>
                    </li>
                </ul>
                <router-view></router-view>
            </div>
        </div>
    </div>
</template>

<script>
    export default {
        name: "CharacterOverview"
    }
</script>
