// resources/js/apps/campaign/components/Spells/SpellbookButton/SpellbookButton.tsx
import { FC } from "react";
import { SpellbookButtonProps } from "./types";

const SpellbookButton: FC<SpellbookButtonProps> = ({ button, children, icon, name }) => {
  if (button) {
    return <button data-uk-toggle="target: #spellbook-modal" className="uk-button uk-button-secondary" type="button">
      {icon ? <i className="fas fa-book fa-fw"></i> : null}
      {children}
    </button>
  }

  return <a href="/" title="Spellbook" data-uk-toggle={`target: #${name}`}>
    {icon ? <i className="fas fa-book fa-fw"></i> : null}
    {children}
  </a>
}

export default SpellbookButton

// resources/js/components/spells/partials/spellbook-button.vue
<template>
    <button v-if="button" uk-toggle="target: #spellbook-modal" class="uk-button uk-button-secondary" type="button">
        <i v-if="icon" class="fas fa-book fa-fw"></i>
        <slot></slot>
    </button>
    <a v-else href="/" title="Spellbook" :uk-toggle="`target: #${name}`">
        <i v-if="icon" class="fas fa-book fa-fw"></i>
        <slot></slot>
    </a>
</template>

<script>
export default {
    props: {
        name: {
            type: String
        },
        button: {
            type: Boolean,
            default: false
        },
        icon: {
            type: Boolean,
            default: false
        },
    },
    name: "spellbook-button"
}
</script>
