// resources/js/admin/components/races/race-overview/race-overview.vue
<template>
    <div id="races">
        <h1>Races</h1>
        <div class="uk-section uk-section-default">
            <div class="uk-container padded">
                <router-link class="uk-button uk-button-primary" :to="{name: 'race-create'}">
                    <i class="fas fa-plus"></i> Add race
                </router-link>
                <paginated-table v-if="(races?.data?.length || 0) > 0"
                                 :actions="ui.actions"
                                 :columns="ui.columns"
                                 :records="races"
                                 :store="store"
                                 @destroy="state.destroy"
                                 searchable/>
            </div>
        </div>
    </div>
</template>

<script>
import PaginatedTable from '@components/partial/paginated-table'
import { storeToRefs } from 'pinia/dist/pinia.esm-browser'
import { onMounted } from 'vue'
import { useRaceStore } from '../../../stores/races'
import { useState } from './race-overview.state'
import { ui } from './race-overview.ui'

export default {
    name: 'race-overview',
    components: { PaginatedTable },
    setup() {
        const store = useRaceStore()
        const { races } = storeToRefs(store)
        const { state } = useState(store)

        onMounted(() => store.load())

        return {
            races,
            state,
            store,
            ui
        }
    }
}
</script>

// resources/js/apps/admin/components/races/RaceOverview/RaceOverview.tsx
import { Link } from "react-router-dom";
import { ui } from './RaceOverview.ui'
import PaginatedTable from "../../../../../components/layout/PaginatedTable";
import { useRaceOverviewState } from "./RaceOverview.state";

const RaceOverview = () => {
  const { destroy, RaceRepository } = useRaceOverviewState()

  return <div id="races">
    <h1>Races</h1>
    <div className="uk-section uk-section-default">
      <div className="uk-container padded">
        <Link className="uk-button uk-button-primary" to="/races/create">
          <i className="fas fa-plus"></i> Add race
        </Link>
        {(
          RaceRepository.races?.data?.length || 0
        ) > 0 ?
          <PaginatedTable
            actions={ui.actions}
            columns={ui.columns}
            records={RaceRepository.races}
            repository={{
              previous: RaceRepository.previous,
              page: RaceRepository.page,
              next: RaceRepository.next,
              load: RaceRepository.load
            }}
            onAction={(type: string, row) => {
              if (type === 'destroy') destroy(row.id)
            }} /> : null}
      </div>
    </div>
  </div>
}

export default RaceOverview
