// resources/js/admin/components/races/race-overview.vue
<template>
    <div id="races">
        <h1>Races</h1>
        <div class="uk-section uk-section-default">
            <div class="uk-container padded">
                <router-link class="uk-button uk-button-primary" :to="{name: 'race-create'}">
                    <i class="fas fa-plus"></i> Add race
                </router-link>
                <paginated-table :actions="actions"
                                 :columns="columns"
                                 module="Races"
                                 :records="races"
                                 @destroy="destroy"
                                 searchable />
            </div>
        </div>
    </div>
</template>

<script>
import PaginatedTable from "@/components/partial/paginated-table";
import UIKit from "uikit";
import {mapState} from "vuex";

export default {
    name: "race-overview",
    components: {PaginatedTable},
    created() {
        this.$store.dispatch('Races/load');
    },
    data() {
        return {
            actions: [
                {
                    name: 'edit',
                    icon: 'pencil',
                    to: (race) => ({nane: 'race-edit', params: {id: race.id}})
                },
                {
                    name: 'delete',
                    icon: 'trash',
                    classes: 'uk-text-danger'
                }
            ],
            columns: [
                {
                    name: 'name',
                    title: 'Name'
                },
                {
                    name: 'size',
                    title: 'Size',
                },
                {
                    name: 'speed',
                    title: 'Speed',
                    format: (speed) => `${speed}ft.`
                }
            ]
        }
    },
    methods: {
        destroy(race) {
            UIKit.modal.prompt(
                'Are you sure you want to delete this race? Please write DELETE to confirm', '',
                {
                    labels: {
                        ok: 'Delete',
                        cancel: 'cancel'
                    }
                }
            )
                .then((input) => {
                    if (input === 'DELETE') {
                        this.$store.dispatch('Races/destroy', race)
                            .then(() => {
                                this.$store.dispatch('Races/load');
                            });
                    } else {
                        this.$store.dispatch('Messages/error', 'Invalid input, delete cancelled.')
                    }
                });
        }
    },
    computed: {
        ...mapState('Races', ['races'])
    }
}
</script>

// resources/js/apps/admin/components/races/RaceOverview/RaceOverview.tsx
import { Link } from "react-router-dom";
import { ui } from './RaceOverview.ui'
import PaginatedTable from "../../../../../components/layout/PaginatedTable";
import { useRaceOverviewState } from "./RaceOverview.state";

const RaceOverview = () => {
  const { destroy, RaceRepository } = useRaceOverviewState()

  return <div id="races">
    <h1>Races</h1>
    <div className="uk-section uk-section-default">
      <div className="uk-container padded">
        <Link className="uk-button uk-button-primary" to="/races/create">
          <i className="fas fa-plus"></i> Add race
        </Link>
        {(
          RaceRepository.races?.data?.length || 0
        ) > 0 ?
          <PaginatedTable
            actions={ui.actions}
            columns={ui.columns}
            records={RaceRepository.races}
            repository={{
              previous: RaceRepository.previous,
              page: RaceRepository.page,
              next: RaceRepository.next,
              load: RaceRepository.load
            }}
            onAction={(type: string, row) => {
              if (type === 'destroy') destroy(row.id)
            }} /> : null}
      </div>
    </div>
  </div>
}

export default RaceOverview
