// resources/js/components/partial/permissions-form.vue
<template>
    <div class="permissions">
        <div class="uk-margin">
            <p>Do you want to override the standard permissions per user?</p>
            <label><input class="uk-radio" type="radio" :value="true" v-model="override"> Yes</label>
            <label><input class="uk-radio" type="radio" :value="false" v-model="override"> No</label>
        </div>
        <table class="uk-table" v-if="override && permissions != null && users != null">
            <thead>
            <tr>
                <th>User</th>
                <th>
                    <label>
                        <input type="checkbox" class="uk-checkbox" @change.prevent="selectAll('view')"
                               :checked="selected.view"> View
                    </label>
                </th>
                <th>
                    <label>
                        <input type="checkbox" class="uk-checkbox" @change.prevent="selectAll('create')"
                               :checked="selected.create"> Create
                    </label>
                </th>
                <th>
                    <label>
                        <input type="checkbox" class="uk-checkbox" @change.prevent="selectAll('edit')"
                               :checked="selected.edit"> Edit
                    </label>
                </th>
                <th>
                    <label>
                        <input type="checkbox" class="uk-checkbox" @change.prevent="selectAll('delete')"
                               :checked="selected.delete"> Delete
                    </label>
                </th>
            </tr>
            </thead>
            <tbody>
            <tr v-for="user in users.data">
                <td style="text-transform: capitalize;">{{ user.name }}</td>
                <td>
                    <input type="checkbox" class="uk-checkbox" v-model="permissions[user.id].view">
                </td>
                <td>
                    <input type="checkbox" class="uk-checkbox" v-model="permissions[user.id].create">
                </td>
                <td>
                    <input type="checkbox" class="uk-checkbox" v-model="permissions[user.id].edit">
                </td>
                <td>
                    <input type="checkbox" class="uk-checkbox" v-model="permissions[user.id].delete">
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</template>

<script>
    import {mapState} from "vuex";

    export default {
        name: "permissions-form",
        props: ['value'],
        mounted() {
            this.$store.dispatch('Users/load')
                .then(() => {
                    let permissions = {};
                    for (let user of this.users.data) {
                        permissions[user.id] = this.value[user.id] || {
                            view: false,
                            edit: false,
                            create: false,
                            delete: false,
                        };
                    }
                    this.$set(this, 'permissions', permissions);
                });
            this.override = Object.keys(this.value || {}).length > 0;
        },
        data() {
            return {
                override: false,
                permissions: null,
                selected: {
                    view: false,
                    create: false,
                    edit: false,
                    delete: false
                }
            }
        },
        methods: {
            selectAll(type) {
                this.selected[type] = !this.selected[type];
                for (let index in this.value) {
                    let permission = this.value[index];
                    permission[type] = this.selected[type];
                }
            }
        },
        computed: {
            ...mapState('Users',['users'])
        },
        watch: {
            permissions: {
                deep: true,
                handler() {
                    if (this.override) {
                        this.$emit('input', this.permissions);
                    }
                }
            },
            override(value) {
                this.$emit('input', value ? this.permissions : {});
            }
        }
    }
</script>

// resources/js/apps/campaign/components/Common/Form/PermissionsForm/PermissionsForm.tsx
import { Action } from "@dnd/types";
import classNames from "classnames";
import { FC } from "react";
import { usePermissionsFormState } from "./PermissionsForm.state";
import { PermissionFormProps } from "./types";

const PermissionForm: FC<PermissionFormProps> = ({ entity, id, value, className, onChange }) => {
  const { input, override, selected, setOverride, selectAll, toggle, users } = usePermissionsFormState(
    entity,
    onChange,
    id,
    value
  )
  const actions: Action[] = [ 'view', 'edit', 'delete' ]

  return <div className={classNames("permissions", className)}>
    <div className="uk-margin">
      <p>Do you want to override the standard permissions per user?</p>
      <label className="uk-margin-right">
        <input className="uk-radio"
               type="radio"
               value={1}
               checked={override}
               onChange={(e) => setOverride(e.target.checked)} /> Yes
      </label>
      <label>
        <input className="uk-radio"
               type="radio"
               value={0}
               checked={!override}
               onChange={(e) => setOverride(!e.target.checked)} /> No
      </label>
    </div>
    {
      override && input !== null && users !== null ?
        <table className="uk-table">
          <thead>
          <tr>
            <th>User</th>
            {
              actions.map((action) => <th key={`action-${action}`}>
                <label style={{ textTransform: 'capitalize' }}>
                  <input className="uk-checkbox uk-margin-small-right"
                         type="checkbox"
                         checked={selected[action]}
                         onChange={() => selectAll(action)} /> {action}
                </label>
              </th>)
            }
          </tr>
          </thead>
          <tbody>
          {
            users.map((user) => <tr key={`user-${user.id}`}>
              <td style={{ textTransform: 'capitalize' }}>{user.name}</td>
              {actions.map((action) => <td key={`user-${user.id}-${action}`}>
                  <input type="checkbox"
                         className="uk-checkbox"
                         onChange={(e) => toggle(user.id, action, e.target.checked)}
                         checked={!!(
                           input[user.id]?.[action]
                         )} />
                </td>
              )}
            </tr>)
          }
          </tbody>
        </table>
        : null
    }
  </div>
}

export default PermissionForm
