// resources/vue/campaign/components/partial/permissions-form/permissions-form.vue
<template>
    <div class="permissions">
        <div class="uk-margin">
            <p>Do you want to override the standard permissions per user?</p>
            <label class="uk-margin-right"><input class="uk-radio" type="radio" :value="true" v-model="state.override">
                Yes
            </label>
            <label><input class="uk-radio" type="radio" :value="false" v-model="state.override"> No</label>
        </div>
        <table class="uk-table" v-if="state.override && state.input != null && users != null">
            <thead>
            <tr>
                <th>User</th>
                <th>
                    <label>
                        <input type="checkbox" class="uk-checkbox" @change.prevent="state.selectAll('view')"
                               :checked="state.selected.view"> View
                    </label>
                </th>
                <th>
                    <label>
                        <input type="checkbox" class="uk-checkbox" @change.prevent="state.selectAll('create')"
                               :checked="state.selected.create"> Create
                    </label>
                </th>
                <th>
                    <label>
                        <input type="checkbox" class="uk-checkbox" @change.prevent="state.selectAll('edit')"
                               :checked="state.selected.edit"> Edit
                    </label>
                </th>
                <th>
                    <label>
                        <input type="checkbox" class="uk-checkbox" @change.prevent="state.selectAll('delete')"
                               :checked="state.selected.delete"> Delete
                    </label>
                </th>
            </tr>
            </thead>
            <tbody>
            <tr v-for="user in users.data">
                <td style="text-transform: capitalize;">{{ user.name }}</td>
                <td>
                    <input type="checkbox" class="uk-checkbox" v-model="state.input[user.id].view">
                </td>
                <td>
                    <input type="checkbox" class="uk-checkbox" v-model="state.input[user.id].create">
                </td>
                <td>
                    <input type="checkbox" class="uk-checkbox" v-model="state.input[user.id].edit">
                </td>
                <td>
                    <input type="checkbox" class="uk-checkbox" v-model="state.input[user.id].delete">
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</template>

<script>
import { usePermissionStore } from '@campaign/stores/permissions'
import { useUserStore } from '@campaign/stores/users'
import { storeToRefs } from 'pinia/dist/pinia.esm-browser'
import { onMounted, watch } from 'vue'
import { usePermissionsFormState } from './permissions-form.state'

export default {
    name: 'permissions-form',
    props: ['value', 'entity', 'id'],
    emits: ['input'],
    setup(props, ctx) {
        const userStore = useUserStore()
        const permissionStore = usePermissionStore()
        const { users } = storeToRefs(userStore)
        const { permissions } = storeToRefs(permissionStore)
        const state = usePermissionsFormState(props.entity, props.id)

        onMounted(() => {
            const promises = [
                permissionStore.fetch({ entity: props.entity, id: props.id }),
                userStore.load()
            ]
            Promise.all(promises)
                .then(() => {
                    state.init(users, permissions)
                })
        })

        watch(() => state.override, () => {
            ctx.emit('input', props.value ? state.input.value : {})
        })

        watch(() => state.input, () => {
            if (state.override) {
                ctx.emit('update:modelValue', state.input)
            }
        }, { deep: true })

        return { users, state }
    }
}
</script>

// resources/js/apps/campaign/components/Common/Form/PermissionsForm/PermissionsForm.tsx
import { Action } from "@dnd/types";
import classNames from "classnames";
import { FC } from "react";
import { usePermissionsFormState } from "./PermissionsForm.state";
import { PermissionFormProps } from "./types";

const PermissionForm: FC<PermissionFormProps> = ({ entity, id, value, className, onChange }) => {
  const { input, override, selected, setOverride, selectAll, toggle, users } = usePermissionsFormState(
    entity,
    onChange,
    id,
    value
  )
  const actions: Action[] = [ 'view', 'edit', 'delete' ]

  return <div className={classNames("permissions", className)}>
    <div className="uk-margin">
      <p>Do you want to override the standard permissions per user?</p>
      <label className="uk-margin-right">
        <input className="uk-radio"
               type="radio"
               value={1}
               checked={override}
               onChange={(e) => setOverride(e.target.checked)} /> Yes
      </label>
      <label>
        <input className="uk-radio"
               type="radio"
               value={0}
               checked={!override}
               onChange={(e) => setOverride(!e.target.checked)} /> No
      </label>
    </div>
    {
      override && input !== null && users !== null ?
        <table className="uk-table">
          <thead>
          <tr>
            <th>User</th>
            {
              actions.map((action) => <th key={`action-${action}`}>
                <label style={{ textTransform: 'capitalize' }}>
                  <input className="uk-checkbox uk-margin-small-right"
                         type="checkbox"
                         checked={selected[action]}
                         onChange={() => selectAll(action)} /> {action}
                </label>
              </th>)
            }
          </tr>
          </thead>
          <tbody>
          {
            users.map((user) => <tr key={`user-${user.id}`}>
              <td style={{ textTransform: 'capitalize' }}>{user.name}</td>
              {actions.map((action) => <td key={`user-${user.id}-${action}`}>
                  <input type="checkbox"
                         className="uk-checkbox"
                         onChange={(e) => toggle(user.id, action, e.target.checked)}
                         checked={!!(
                           input[user.id]?.[action]
                         )} />
                </td>
              )}
            </tr>)
          }
          </tbody>
        </table>
        : null
    }
  </div>
}

export default PermissionForm
