// resources/js/apps/campaign/components/common/layout/Navigation/Navigation.tsx
import classNames from "classnames";
import { Link } from "react-router-dom";
import { useAuthRepository } from "../../../../../../repositories/AuthRepository";
import SpellbookButton from "../../../spells/SpellbookButton";
import SpellbookModal from "../../../spells/SpellbookModal";
import { useNavigationState } from "./Navigation.state";

const Navigation = () => {
  const { user } = useAuthRepository()
  const { logout, navigation } = useNavigationState()

  if (!user) return null

  return <aside id="left-col" className="uk-light uk-visible@m">
    <div className="left-logo uk-flex uk-flex-middle">DUNGEONS & DIARIES</div>
    {
      user && user.hasOwnProperty('permissions') ? <div className="left-nav-wrap">
        <ul className="uk-nav uk-nav-default" data-uk-nav>
          {
            navigation.map((section) => (
              [
                <li key={`section-${section.title}`} className="uk-nav-header">{section.title}</li>,
                ...section.items.map((item) => <li key={`section-${section.title}-${item.to}`} className={classNames({
                  'uk-open': window.location.pathname ===
                    item.to
                })}>
                  <Link to={item.to}><i className={`fas fa-${item.icon} fa-fw`}></i> {item.title}</Link>
                </li>)
              ]
            ))
          }
        </ul>
      </div> : null
    }
    <div className="bar-bottom">
      <ul className="uk-subnav uk-flex uk-flex-center uk-child-width-1-5" data-uk-grid>
        <li><Link to="/dashboard" title="Home"><i className="fas fa-home fa-fw"></i></Link></li>
        <li><a href="/profile" title="Settings"><i className="fas fa-sliders-h fa-fw"></i></a></li>
        <li><SpellbookButton icon={true} name="spellbook-modal" /></li>
        <li>
          <a href="/logout" title="Sign out" onClick={logout}>
            <i className="fas fa-sign-out-alt fa-fw"></i>
          </a>
        </li>
      </ul>
    </div>
    <SpellbookModal name="navbar-spellbook" />
  </aside>
}

export default Navigation

// resources/js/components/layout/navigation.vue
<template>
    <aside id="left-col" class="uk-light uk-visible@m">
        <div class="left-logo uk-flex uk-flex-middle">
            DUNGEONS & DIARIES
        </div>

        <div class="left-nav-wrap" v-if="user && user.hasOwnProperty('permissions')">
            <ul class="uk-nav uk-nav-default" data-uk-nav>
                <li class="uk-nav-header">CAMPAIGN</li>
                <li v-if="$store.getters.can('view', 'character')">
                    <router-link :to="{name: 'player-characters'}">
                        <i class="fas fa-users fa-fw"></i> Characters
                    </router-link>
                </li>
                <li v-if="$store.getters.can('view', 'location')">
                    <router-link :to="{name: 'locations'}">
                        <i class="fas fa-map-marked-alt fa-fw"></i> Locations
                    </router-link>
                </li>
                <li v-if="$store.getters.can('view', 'quest')">
                    <router-link :to="{name: 'quests'}">
                        <i class="fas fa-exclamation fa-fw"></i> Quests
                    </router-link>
                </li>
                <li v-if="$store.getters.can('view', 'note')">
                    <router-link :to="{name: 'notes'}">
                        <i class="fas fa-book-open fa-fw"></i> Notes
                    </router-link>
                </li>
                <li>
                    <router-link :to="{name: 'inventory'}">
                        <i class="fas fa-shopping-bag fa-fw"></i> Inventory
                    </router-link>
                </li>
                <li class="uk-nav-header">PLATFORM</li>
                <li v-if="$store.getters.can('view', 'user')">
                    <router-link :to="{name: 'users'}">
                        <i class="fas fa-users-cog fa-fw"></i> Users
                    </router-link>
                </li>
                <li v-if="$store.getters.can('view', 'role')">
                    <router-link :to="{name: 'roles'}">
                        <i class="fas fa-user-lock fa-fw"></i> Campaign roles
                    </router-link>
                </li>
            </ul>
        </div>
        <div class="bar-bottom">
            <ul class="uk-subnav uk-flex uk-flex-center uk-child-width-1-5" data-uk-grid>
                <li><router-link :to="{name: 'dashboard'}" title="Home"><i class="fas fa-home fa-fw"></i></router-link></li>
                <li><a href="/profile" title="Settings"><i class="fas fa-sliders-h fa-fw"></i></a></li>
                <li><spellbook-button icon name="spellbook-modal"></spellbook-button></li>
                <li>
                    <a href="/logout" title="Sign out" @click.prevent="$store.dispatch('logout')">
                        <i class="fas fa-sign-out-alt fa-fw"></i>
                    </a>
                </li>
            </ul>
        </div>
        <spellbook-modal />
    </aside>
</template>

<script>
    import {mapState} from 'vuex';
    import SpellbookModal from "../spells/partials/spellbook-modal";
    import SpellbookButton from "../spells/partials/spellbook-button";

    export default {
        name: "Navigation",
        components: {SpellbookButton, SpellbookModal},
        methods: {
            logout() {
                axios.post('/logout')
                    .then(() => {
                        document.location.href = '/';
                    });
            }
        },
        computed: {
            ...mapState(['user'])
        }
    }
</script>
