// resources/js/admin/components/races/partial/language-select-modal.vue
<template>
    <div>
        <button class="uk-button uk-button-primary" type="button" uk-toggle="target: #lang-select-modal">
            Select language
        </button>
        <div id="lang-select-modal" uk-modal @beforehide="reset()">
            <div class="uk-modal-dialog uk-modal-body">
                <h2 class="uk-modal-title">Select a language proficiency</h2>
                <div class="uk-margin">
                    <select name="language" id="language" class="uk-select" v-model="language.id">
                        <option :value="0">- Make a choice -</option>
                        <option v-for="language in languages" :value="language.id" :disabled="selected.includes(language.id)">
                            {{ language.name }}
                        </option>
                    </select>
                </div>
                <div class="uk-margin">
                    <label for="language-optional">
                        <input id="language-optional" class="uk-checkbox" type="checkbox" v-model="language.optional"> Optional
                    </label>
                </div>
                <div class="uk-margin">
                    <button class="uk-button uk-button-primary" type="button" @click.prevent="save">Select</button>
                </div>
                <button class=" uk-modal-close-default uk-close-large" type="button" uk-close></button>
            </div>
        </div>
    </div>
</template>

<script>
import {mapState} from "vuex";
import UIKit from "uikit";

export default {
    name: "language-select-modal",
    props: {
        selected: {
            type: Array,
            default: () => []
        }
    },
    data() {
        return {
            language: {
                id: 0,
                optional: false
            }
        }
    },
    computed: {
        ...mapState(['languages'])
    },
    methods: {
        save() {
            if (this.language.id > 0) {
                this.$emit('input', this.language)
                this.close()
            }
        },
        reset() {
            this.$set(this, 'language', {id: 0, optional: false})
        },
        close() {
            UIKit.modal('#lang-select-modal').hide()
        }
    }
}
</script>

// resources/js/apps/admin/components/races/RaceForm/components/LanguageSelectModal/LanguageSelectModal.tsx
import { FC } from "react";
import InputSelect from "../../../../../../../components/layout/form/components/InputSelect";
import InputBoolean from "../../../../../../../components/layout/form/components/InputBoolean";
import { useLanguageModalState } from "./LanguageSelectModal.state";
import { LanguageModalProps } from "./types";
import Modal from "../../../../../../../components/layout/Modal";

const LanguageSelectModal: FC<LanguageModalProps> = ({ selected, onChange }) => {
  const { input, options, save, update } = useLanguageModalState(selected, onChange)

  return <div>
    <Modal id="lang-select-modal" title="Select a language proficiency" trigger={
      <button className="uk-button uk-button-primary" type="button">
        Select language
      </button>}>
      {
        input === null ? null :
          <>
            <InputSelect
              id="language"
              name="language"
              label=""
              emptyLabel="Choose a language"
              options={options}
              initialValue={input.id}
              onChange={(value) => update('id', value)} />
            <InputBoolean
              id="language-optional"
              name="language-optional"
              label="Optional"
              onChange={(value) => update('optional', value)}
              initialValue={input.optional} />
            <div className="uk-margin">
              <button className="uk-button uk-button-primary" type="button" onClick={(e) => {
                e.preventDefault()
                save()
              }}>Select
              </button>
            </div>
          </>
      }
    </Modal>
  </div>
}

export default LanguageSelectModal
