// resources/js/admin/components/Admin.vue
<template>
    <div id="admin-app">
        <header-navbar />
        <navigation>
            <aside id="left-col" class="uk-light uk-visible@m">
                <div class="left-logo uk-flex uk-flex-middle">
                    DUNGEONS & DIARIES
                </div>

                <div class="left-nav-wrap">
                    <ul class="uk-nav uk-nav-default" data-uk-nav>
                        <li :key="i" v-for="i in 5">
                            <span class="navigation-placeholder">&nbsp;</span>
                        </li>
                    </ul>
                </div>
            </aside>
        </navigation>
        <messages></messages>
        <div id="content" uk-height-viewport="expand: true">
            <div class="uk-container uk-container-expand">
                <router-view>
                    <div class="uk-section uk-section-default">
                        <div class="uk-container padded">
                            &nbsp;
                        </div>
                    </div>
                </router-view>
                <footer class="uk-section uk-section-small uk-text-center">
                    <hr>
                    <p class="uk-text-small uk-text-center">
                        Made with love by <a href="https://bit.ly/2Rz0xNG" target="_blank">Tim van Dijck</a>
                    </p>
                </footer>
            </div>
        </div>
    </div>
</template>

<script>
import Messages from "@components/layout/messages";
import Navigation from "@admin/components/layout/navigation";
import HeaderNavbar from "@components/layout/header-navbar";

export default {
    name: "Admin",
    components: {HeaderNavbar, Navigation, Messages}
}
</script>

// resources/js/apps/admin/components/Admin.tsx
import { BrowserRouter, Route, Routes } from "react-router-dom";
import HeaderNavbar from "../../../components/layout/HeaderNavbar";
import { MessagesProvider } from "../../../components/layout/Messages";
import router from '../router'
import Navigation from "./layout/Navigation";

const Admin = () => {
  return (
    <>
      <div id="admin-app">
        <BrowserRouter basename="/admin">
          <HeaderNavbar />
          <Navigation />
          <MessagesProvider>
            <div id="content" data-uk-height-viewport="expand: true">
              <div className="uk-container uk-container-expand">
                <div className="uk-section uk-section-default">
                  <div className="uk-container padded">
                    <Routes>
                      {router.map((route) =>
                        <Route key={route.path} path={route.path} element={route.element} />)}
                    </Routes>
                  </div>
                </div>
                <footer className="uk-section uk-section-small uk-text-center">
                  <hr />
                  <p className="uk-text-small uk-text-center">
                    Made with love by <a href="https://bit.ly/2Rz0xNG" target="_blank">Tim van Dijck</a>
                  </p>
                </footer>
              </div>
            </div>
          </MessagesProvider>
        </BrowserRouter>
      </div>
    </>
  )
}

export default Admin
