// resources/js/admin/components/races/race-form/components/trait-select-modal/trait-select-modal.vue
<template>
    <div>
        <button class="uk-button uk-button-primary" type="button" uk-toggle="target: #trait-select-modal">
            Select race trait
        </button>
        <div id="trait-select-modal" uk-modal @beforehide="state.reset()">
            <div class="uk-modal-dialog uk-modal-body">
                <h2 class="uk-modal-title">Select a race trait</h2>
                <div class="uk-margin">
                    <select name="trait" id="trait" class="uk-select" v-model="state.trait.id">
                        <option :value="0">- Choose a trait -</option>
                        <option v-for="option in state.traitOptions" :value="option.id"
                                :disabled="selected.includes(option.id)">{{ option.name }}
                        </option>
                    </select>
                </div>
                <div v-if="state.selectedTrait" v-html="state.selectedTrait.description"></div>
                <hr>
                <div uk-accordion>
                    <div class="accordion">
                        <div class="uk-accordion-title">
                            <h2>or create a new one</h2>
                        </div>
                        <div class="uk-accordion-content">
                            <div class="uk-margin">
                                <label for="trait-name" class="uk-form-label">Name*</label>
                                <input id="trait-name" name="name" type="text" class="uk-input"
                                       v-model="state.trait.name">
                            </div>
                            <div class="uk-margin">
                                <label for="trait-description" class="uk-form-label">Description</label>
                                <html-editor id="trait-description" name="trait-description"
                                             v-model="state.trait.description"
                                             height="600"></html-editor>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="uk-margin">
                    <button class="uk-button uk-button-primary" type="button" @click.prevent="state.save">Select
                    </button>
                </div>
                <button class=" uk-modal-close-default uk-close-large" type="button" uk-close></button>
            </div>
        </div>
    </div>
</template>

<script>
import HtmlEditor from "../../../../../../components/partial/html-editor"
import { useStore } from "vuex"
import { onMounted } from "vue"
import { ui } from './trait-select-modal.ui'

export default {
    name: "trait-select-modal",
    components: { HtmlEditor },
    props: {
        selected: {
            type: Array,
            default: () => []
        }
    },
    setup(props, ctx) {
        const store = useStore()
        const state = useState(ctx, ui)

        onMounted(() => {
            store.dispatch('Races/loadTraits')
            ui.initEditorOnShow()
            ui.removeEditorOnHide()
        })

        return { state, selected: props.selected }
    }
}
</script>

// resources/js/apps/admin/components/races/RaceForm/components/TraitSelectModal/TraitSelectModal.tsx
import InputSelect from "../../../../../../../components/layout/form/components/InputSelect";
import InputText from "../../../../../../../components/layout/form/components/InputText";
import InputRichText from "../../../../../../../components/layout/form/components/InputRichText";
import { FC } from "react";
import { TraitModalProps } from "./types";
import { useTraitModalState } from "./TraitSelectModal.state";
import Modal from "../../../../../../../components/layout/Modal";

const TraitSelectModal: FC<TraitModalProps> = ({ selected, onChange }) => {
  const { input, options, save, selectedTrait, update } = useTraitModalState(selected, onChange)

  return <div>
    <Modal id="trait-select-modal"
           title="Select a race trait"
           trigger={<button className="uk-button uk-button-primary" type="button">
             Select race trait
           </button>}>
      {
        input === null ?
          null :
          <>
            <InputSelect id="trait" name="trait" label=""
                         options={options}
                         initialValue={input.id}
                         onChange={(value) => update('id', value)} />
            {selectedTrait ? <div dangerouslySetInnerHTML={{ __html: selectedTrait.description }}></div> : null}
            <hr />
            <div data-uk-accordion>
              <div className="accordion">
                <div className="uk-accordion-title">
                  <h2>or create a new one</h2>
                </div>
                <div className="uk-accordion-content">
                  <InputText id="trait-name"
                             name="trait-name"
                             label="Name"
                             onChange={(value) => update('name', value)}
                             required />
                  <InputRichText onChange={(value) => update('description', value)}
                                 id="trait-description"
                                 name="trait-description"
                                 label="Description" />
                </div>
              </div>
            </div>
            <div className="uk-margin">
              <button className="uk-button uk-button-primary" type="button"
                      onClick={(e) => {
                        e.preventDefault()
                        save()
                      }}>Select
              </button>
            </div>
            <button className=" uk-modal-close-default uk-close-large" type="button" data-uk-close />
          </>
      }
    </Modal>
  </div>
}

export default TraitSelectModal
