// resources/js/apps/campaign/components/Characters/PlayerCharacters/PlayerCharacterOverview/PlayerCharacterOverview.tsx
import { Link } from 'react-router-dom'
import PaginatedTable from '../../../../../../components/layout/PaginatedTable'
import { useCharacterOverviewState } from './PlayerCharacterOverview.state'
import { usePlayerCharacterOverviewUi } from './PlayerCharacterOverview.ui'

const PlayerCharacterOverview = () => {
  const { characterRepository, destroy } = useCharacterOverviewState()
  const { actions, columns } = usePlayerCharacterOverviewUi()

  return <div className="player-characters">
    <Link className="uk-button uk-button-primary" to="/characters/players/create">
      <i className="fas fa-plus"></i> Add character
    </Link>
    {
      (
        characterRepository.characters !== null && characterRepository.characters.data.length > 0
      ) ?
        <PaginatedTable
          actions={actions}
          columns={columns}
          repository={{
            previous: characterRepository.previous,
            page: characterRepository.page,
            next: characterRepository.next,
            load: characterRepository.load
          }}
          records={characterRepository.characters}
          onAction={(type: string, row) => {
            if (type === 'destroy') characterRepository.destroy(row.id)
          }}
        /> :
        <p className="uk-text-center">
          {
            characterRepository.characters == null ?
              <i className="fas fa-sync fa-spin fa-2x" /> :
              <span>No characters found</span>
          }
        </p>
    }
  </div>
}

export default PlayerCharacterOverview

// resources/vue/campaign/components/characters/player-character-overview/player-character-overview.vue
<template>
    <div class="player-characters">
        <router-link class="uk-button uk-button-primary" :to="{name: 'pc-create', params: {type: 'player'}}">
            <i class="fas fa-plus"></i> Add character
        </router-link>
        <paginated-table v-if="characters != null && characters.data.length > 0"
                         :actions="ui.actions"
                         :columns="ui.columns"
                         :store="store"
                         :records="characters"
                         @destroy="state.destroy"/>
        <p v-else class="uk-text-center">
            <i v-if="characters == null" class="fas fa-sync fa-spin fa-2x"></i>
            <span v-else>
                No characters found
            </span>
        </p>
    </div>
</template>

<script>
import { useCharacterStore } from '@campaign/stores/characters'
import PaginatedTable from '@components/partial/paginated-table'
import { storeToRefs } from 'pinia/dist/pinia.esm-browser'
import { onMounted } from 'vue'
import { useCharacterOverviewState } from './player-character-overview.state'
import { ui } from './player-character-overview.ui'

export default {
    name: 'PlayerCharacterOverview',
    components: { PaginatedTable },
    setup() {
        const store = useCharacterStore()
        const { characters } = storeToRefs(store)
        const state = useCharacterOverviewState(store)

        onMounted(() => {
            store.load('player')
            store.loadRaces()
        })

        return { characters, state, store, ui }
    }
}
</script>
