// resources/js/apps/admin/components/users/UserForm/UserForm.tsx
import InputText from "../../../../../components/layout/form/components/InputText";
import InputEmail from "../../../../../components/layout/form/components/InputEmail";
import InputBoolean from "../../../../../components/layout/form/components/InputBoolean/InputBoolean";
import FormButtons from "../../../../../components/layout/form/components/FormButtons";
import { useParams } from "react-router";
import { useUserFormState } from "./UserForm.state";
import { useNavigate } from "react-router-dom";

const UserForm = () => {
  const navigate = useNavigate()
  const { id } = useParams() as { id: number | undefined }
  const { user, errors, submit, onUpdate } = useUserFormState(id)

  const title = id ? `Edit ${user ? user.name : 'user'}` : 'Add user'

  return (
    <div>
      <h1>{title}</h1>
      <div className="uk-section uk-section-default">
        <div className="uk-container padded">
          {
            user ?
              <form className="uk-form-stacked" onSubmit={submit}>
                <InputText id="name"
                           name="name"
                           label="Name"
                           initialValue={user.name}
                           errors={errors?.name}
                           onChange={(value) => onUpdate('name', value)} />
                <InputEmail id="email"
                            name="email"
                            label="E-mail"
                            initialValue={user.email}
                            errors={errors?.email}
                            onChange={(value) => onUpdate('email', value)} />
                <InputBoolean id="admin"
                              name="admin"
                              label="Administrator"
                              initialValue={user.admin}
                              onChange={(value) => onUpdate('admin', value)} />
                <InputBoolean id="active"
                              name="active"
                              label="Active"
                              initialValue={user.active}
                              onChange={(value) => onUpdate('active', value)} />
                <FormButtons cancel={() => navigate('/users')} />
              </form>
              :
              <p className="uk-text-center">
                <i className="fas fa-2x fa-sync fa-spin"></i>
              </p>
          }
        </div>
      </div>
    </div>
  )
}

export default UserForm

// resources/js/admin/components/users/user-form/user-form.vue
<template>
    <div>
        <h1>{{ ui.title.value }}</h1>
        <div class="uk-section uk-section-default">
            <div class="uk-container padded">
                <form v-if="state.user" class="uk-form-stacked">
                    <div class="uk-margin">
                        <label for="name" class="uk-form-label"
                               :class="{'uk-text-danger': state.errors.hasOwnProperty('name')}">Name*</label>
                        <input id="name" title="name" type="text" class="uk-input"
                               :class="{'uk-form-danger': state.errors.hasOwnProperty('name')}"
                               v-model="state.user.name">
                    </div>
                    <div class="uk-margin">
                        <label for="email" class="uk-form-label"
                               :class="{'uk-text-danger': state.errors.hasOwnProperty('email')}">Email address*</label>
                        <input id="email" title="email" type="text" class="uk-input"
                               :class="{'uk-form-danger': state.errors.hasOwnProperty('email')}"
                               v-model="state.user.email">
                    </div>
                    <div class="uk-margin">
                        <label class="uk-form-label"
                               :class="{'uk-text-danger': state.errors.hasOwnProperty('admin')}">
                            <input id="admin" class="uk-checkbox" type="checkbox"
                                   v-model="state.user.admin"> Administrator
                        </label>
                    </div>
                    <div class="uk-margin">
                        <label class="uk-form-label"
                               :class="{'uk-text-danger': state.errors.hasOwnProperty('active')}">
                            <input id="active" class="uk-checkbox" type="checkbox"
                                   v-model="state.user.active"> Active
                        </label>
                    </div>
                    <p class="uk-margin">
                        <button class="uk-button uk-button-primary uk-margin-right" @click.prevent="state.save">Save
                        </button>
                        <router-link class="uk-button uk-button-danger" :to="{name: 'users'}">
                            Cancel
                        </router-link>
                    </p>
                </form>
                <p v-else class="uk-text-center">
                    <i class="fas fa-2x fa-sync fa-spin"></i>
                </p>
            </div>
        </div>
    </div>
</template>

<script>
import { computed, onMounted } from 'vue'
import { useMessageStore } from '../../../../stores/messages'
import { useUserStore } from '../../../stores/users'
import { useUserFormState } from './user-form.state'

export default {
    name: 'user-form',
    setup(props) {
        const store = useUserStore()
        const messages = useMessageStore()
        const { state } = useUserFormState(store, messages)
        const title = computed(() => props.id ? `Edit ${state.user ? state.user.name : 'user'}` : 'Add user')

        onMounted(() => {
            if (props.id) {
                store.find(props.id)
                    .then((userFromState) => state.setUser(userFromState))
            } else {
                state.setUser({ name: '', email: '' })
            }
        })


        return {
            state,
            ui: {
                title
            }
        }
    },
    props: {
        id: {
            required: false
        }
    }
}
</script>
