// resources/js/apps/admin/components/users/UserDetail/UserDetail.tsx
import { Link } from "react-router-dom"
import classNames from "classnames";
import { useUserDetailState } from "./UserDetail.state";
import { useParams } from "react-router";

const UserDetail = () => {
  const { id } = useParams() as { id: number | undefined }
  const { user, campaigns, resetPassword } = useUserDetailState(id)

  return <>
    {
      user ?
        <div id="user">
          <h1>
            <Link className="uk-link-text" to="/users"><i className="fas fa-chevron-left" /></Link>
            {user.name} {
            user.admin ? <span title="Campaign">(<i
              className="fas fa-user-shield" />)</span> : null}
          </h1>
          <div data-uk-grid>
            <div className="uk-width-1-1@s uk-width-1-3@l">
              <h2>Info</h2>
              <div className="uk-margin uk-flex uk-flex-between">
                <b>Name</b>
                <span>{user.name}</span>
              </div>
              <div className="uk-margin uk-flex uk-flex-between">
                <b>Email</b>
                <span>{user.email}</span>
              </div>
              <div className="uk-flex uk-flex-between">
                <b>Status</b>
                <span className={classNames(
                  "uk-label",
                  { 'uk-label-success': user.active, 'uk-label-danger': !user.active }
                )}>
                {user.active ? 'Active' : 'Inactive'}
              </span>
              </div>
            </div>
            <div className="uk-width-1-1@s uk-width-2-3@l">
              <h2>Campaigns</h2>
              <table className="uk-table uk-table-divider">
                <tbody>
                {
                  campaigns === null ?
                    <tr>
                      <td className="uk-text-center" colSpan={2}><i className="fas fa-sync fa-spin" /></td>
                    </tr> :
                    (
                      campaigns || []
                    ).length === 0 ?
                      <tr>
                        <td className="uk-text-center uk-text-italic" colSpan={2}>
                          This user is not part of any campaigns
                        </td>
                      </tr> :
                      campaigns.map((campaign) =>
                        <tr key={campaign.id}>
                          <td>{campaign.name}</td>
                          <td>{}</td>
                        </tr>
                      )
                }
                </tbody>
              </table>
            </div>
          </div>
          <div className="uk-flex uk-margin-large-top">
            <Link to={`/users/${user.id}/edit`} className="uk-button uk-button-primary uk-margin-right">
              <i className="fas fa-edit" /> Edit
            </Link>
            <button className="uk-button" onClick={(e) => {
              e.preventDefault()
              resetPassword()
            }}>
              <i className="fas fa-lock" /> Reset password
            </button>
          </div>
        </div> :
        <div className="uk-section uk-section-default">
          <p className="uk-text-center">
            <i className="fas fa-sync fa-spin fa-2x"></i>
          </p>
        </div>
    }
  </>
}

export default UserDetail

// resources/js/admin/components/users/user-detail/user-detail.vue
<template>
    <div id="user" v-if="state.user">
        <h1>
            <router-link class="uk-link-text" :to="{name: 'users'}"><i class="fas fa-chevron-left"/>
            </router-link>
            {{ state.user.name }} <span v-if="state.user.admin" title="Admin">(<i
            class="fas fa-user-shield"/>)</span>
        </h1>
        <div uk-grid>
            <div class="uk-width-1-1@s uk-width-1-3@l">
                <h2>Info</h2>
                <div class="uk-margin uk-flex uk-flex-between">
                    <b>Name</b>
                    <span>{{ state.user.name }}</span>
                </div>
                <div class="uk-margin uk-flex uk-flex-between">
                    <b>Email</b>
                    <span>{{ state.user.email }}</span>
                </div>
                <div class="uk-flex uk-flex-between">
                    <b>Status</b>
                    <span class="uk-label"
                          :class="{'uk-label-success': state.user.active, 'uk-label-danger': !state.user.active}">
                        {{ state.user.active ? 'Active' : 'Inactive' }}
                    </span>
                </div>
            </div>
            <div class="uk-width-1-1@s uk-width-2-3@l">
                <h2>Campaigns</h2>
                <table v-if="state.campaigns">
                    <tbody>
                    <tr v-if="state.campaigns === null">
                        <td class="uk-text-center" colspan="2"><i class="fas fa-sync fa-spin"/></td>
                    </tr>
                    <tr v-else-if="(state.campaigns || []).length === 0">
                        <td class="uk-text-center uk-text-italic" colspan="2">This user is not part of any campaigns
                        </td>
                    </tr>
                    <tr v-else v-for="campaign in state.campaigns">
                        <td>{{ campaign.name }}</td>
                        <td>{{ }}</td>
                    </tr>
                    </tbody>
                </table>

            </div>
        </div>
        <div class="uk-flex uk-margin-large-top">
            <router-link :to="{name: 'user-edit', params: {id: state.user.id}}"
                         class="uk-button uk-button-primary uk-margin-right">
                <i class="fas fa-edit"/> Edit
            </router-link>
            <button class="uk-button" @click.prevent="resetPassword"><i class="fas fa-lock"/> Reset password</button>
        </div>
    </div>
    <div v-else class="uk-section uk-section-default">
        <p class="uk-text-center">
            <i class="fas fa-sync fa-spin fa-2x"></i>
        </p>
    </div>
</template>

<script>
import { useCampaignStore } from '@admin/stores/campaigns'
import { useUserStore } from '@admin/stores/users'
import { onMounted } from 'vue'
import { useModals } from '../../../modals'
import { useUserDetailState } from './user-detail.state'

export default {
    name: 'user-detail',
    props: ['id'],
    setup(props) {
        const users = useUserStore()
        const modals = useModals()
        const campaigns = useCampaignStore()
        const { state } = useUserDetailState()

        onMounted(() => {
            users.find(props.id).then((user) => state.setUser(user))
            campaigns.loadForUser(props.id).then((campaigns) => state.setCampaigns(campaigns))
        })

        const resetPassword = () => {
            modals.confirm(
                `Are you sure you want to send a password reset link to ${state.user.email}?`,
                () => users.resetPassword(state.user.id)
            )
        }

        return { state, resetPassword }
    }
}
</script>
