// resources/js/apps/campaign/components/Spells/SpellbookModal/SpellbookModal.tsx
import { FC } from "react";
import Modal from "../../../../../components/layout/Modal";
import Spellbook from "../Spellbook";
import { SpellbookModalProps } from "./types";

const SpellbookModal: FC<SpellbookModalProps> = ({ name, children }) => {
  return <div id="spellbook">
    {children}
    <Modal id={name} title={<><i className="fas fa-book"></i> Spellbook</>} trigger={<></>}>
      <Spellbook />
      <button className=" uk-modal-close-default uk-close-large" type="button" data-uk-close />
    </Modal>
  </div>
}

export default SpellbookModal

// resources/vue/campaign/components/spells/spellbook-modal/spellbook-modal.vue
<template>
    <div id="spellbook">
        <slot>
        </slot>
        <div :id="name" uk-modal>
            <div class="uk-width-expand uk-modal-dialog uk-modal-body">
                <h2 class="uk-modal-title"><i class="fas fa-book"></i> Spellbook</h2>
                <spellbook></spellbook>
                <button class=" uk-modal-close-default uk-close-large" type="button" uk-close></button>
            </div>
        </div>
    </div>
</template>

<script>
import Spellbook from '../spellbook'

export default {
    props: {
        name: {
            type: String,
            default: 'spellbook-modal'
        }
    },
    name: 'spellbook-modal',
    components: { Spellbook }
}
</script>
