// resources/js/apps/admin/components/races/RaceForm/components/ProficiencySelectModal/ProficiencySelectModal.tsx
import InputSelect from "../../../../../../../components/layout/form/components/InputSelect";
import { useProficiencyModalState } from "./ProficiencySelectModal.state";
import InputBoolean from "../../../../../../../components/layout/form/components/InputBoolean";
import { FC } from "react";
import { ProficiencyModalProps } from "./types";
import Modal from "../../../../../../../components/layout/Modal";

const ProficiencySelectModal: FC<ProficiencyModalProps> = ({ selected, onChange }) => {
  const { input, options, save, update } = useProficiencyModalState(selected, onChange)

  return (
    <div>
      <Modal id="proficiency-select-modal"
             title="Select a proficiency"
             trigger={<button className="uk-button uk-button-primary"
                              type="button"
                              data-uk-toggle="target: #proficiency-select-modal">
               Select proficiency
             </button>}>
        {
          input === null ? null :
            <>
              <InputSelect
                id="proficiency-id"
                name="proficiency-id"
                label=""
                emptyLabel="Choose a proficiency"
                options={options}
                initialValue={input.id}
                onChange={(value) => update('id', value as number)} />
              <InputBoolean onChange={(value) => update('optional', value)}
                            id="proficiency-optional"
                            name="proficiency-optional"
                            label="Optional"
                            initialValue={input.optional} />
              <div className="uk-margin">
                <button className="uk-button uk-button-primary" type="button" onClick={save}>
                  Select
                </button>
              </div>
            </>
        }
      </Modal>
    </div>
  )
}

export default ProficiencySelectModal

// resources/js/admin/components/races/partial/proficiency-select-modal.vue
<template>
    <div>
        <button class="uk-button uk-button-primary" type="button" uk-toggle="target: #proficiency-select-modal">
            Select proficiency
        </button>
        <div id="proficiency-select-modal" uk-modal @beforehide="reset()">
            <div class="uk-modal-dialog uk-modal-body">
                <h2 class="uk-modal-title">Select a proficiency</h2>
                <div class="uk-margin">
                    <select name="proficiency" id="proficiency" class="uk-select" v-model="proficiency.id">
                        <option :value="0">- Choose a proficiency -</option>
                        <optgroup v-for="(options, type) in proficiencyOptions" :label="type">
                            <option v-for="option in options" :value="option.id" :disabled="selected.includes(option.id)">{{ option.name }}</option>
                        </optgroup>
                    </select>
                </div>
                <div class="uk-margin">
                    <label for="proficiency-optional">
                        <input id="proficiency-optional" class="uk-checkbox" type="checkbox" v-model="proficiency.optional"> Optional
                    </label>
                </div>
                <div class="uk-margin">
                    <button class="uk-button uk-button-primary" type="button" @click.prevent="save">Select</button>
                </div>
                <button class=" uk-modal-close-default uk-close-large" type="button" uk-close></button>
            </div>
        </div>
    </div>
</template>

<script>
import {mapState} from "vuex";
import UIKit from "uikit";

export default {
    name: "proficiency-select-modal",
    props: {
        selected: {
            type: Array,
            default: () => []
        }
    },
    data() {
        return {
            proficiency: {
                id: 0,
                optional: false
            }
        }
    },
    computed: {
        ...mapState('Races', ['proficiencies']),
        proficiencyOptions() {
            const proficiencies = {};
            for (const proficiency of this.proficiencies || []) {
                if (!proficiencies.hasOwnProperty(proficiency.type)) {
                    proficiencies[proficiency.type] = []
                }
                proficiencies[proficiency.type].push(proficiency)
            }
            return proficiencies;
        }
    },
    created() {
        this.$store.dispatch('Races/loadProficiencies')
    },
    methods: {
        save() {
            if (this.proficiency.id > 0) {
                this.$emit('input', this.proficiency)
                this.close()
            }
        },
        reset() {
            this.$set(this, 'proficiency', {id: 0, optional: false})
        },
        close() {
            UIKit.modal('#proficiency-select-modal').hide()
        }
    }
}
</script>
