// resources/js/apps/admin/components/users/UserOverview/UserOverview.tsx
import PaginatedTable from "../../../../../components/layout/PaginatedTable";
import { ui } from './UserOverview.ui'
import UserInviteModal from "./components/UserInviteModal";
import { useUserOverviewState } from "./UserOverview.state";

const UserOverview = () => {
  const { userRepository, destroy } = useUserOverviewState()

  return (
    <div id="users">
      <h1>Users</h1>
      <div className="uk-section uk-section-default">
        <UserInviteModal onInvite={userRepository.load} />
        {
          (
            userRepository.users?.data?.length || 0
          ) > 0 ?
            <PaginatedTable actions={ui.actions}
                            columns={ui.columns}
                            records={userRepository.users}
                            repository={{
                              previous: userRepository.previous,
                              page: userRepository.page,
                              next: userRepository.next,
                              load: userRepository.load
                            }}
                            onAction={(type: string, row) => {
                              if (type === 'destroy') destroy(row.id)
                            }} /> : <p className="uk-text-center">{userRepository.users === null ?
              <i className="fas fa-sync fa-spin fa-2x"></i> :
              <span>No campaigns found</span>}
            </p>
        }
      </div>
    </div>
  )
}

export default UserOverview

// resources/js/admin/components/users/user-overview/user-overview.vue
<template>
    <div id="users">
        <h1>Users</h1>
        <div class="uk-section uk-section-default">
            <div class="uk-container padded">
                <user-invite-modal @invite="() => store.load()"/>
                <paginated-table v-if="(users?.data?.length || 0) > 0"
                                 :actions="ui.actions"
                                 :columns="ui.columns"
                                 :records="users"
                                 :store="store"
                                 @destroy="state.destroy"
                                 searchable/>
            </div>
        </div>
    </div>
</template>

<script>
import PaginatedTable from '@components/partial/paginated-table'
import { storeToRefs } from 'pinia/dist/pinia.esm-browser'
import { onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { useUserStore } from '../../../stores/users'
import UserInviteModal from './components/user-invite-modal/user-invite-modal'
import { useUserOverviewState } from './user-overview.state'
import { ui } from './user-overview.ui'

export default {
    name: 'user-overview',
    components: { UserInviteModal, PaginatedTable },
    setup() {
        const router = useRouter()
        const store = useUserStore()
        const { users } = storeToRefs(store)
        const state = useUserOverviewState(store)
        onMounted(() => store.load())
        return { router, state, store, ui, users }
    }
}
</script>
