// resources/js/admin/components/races/race-form/components/ability-bonus-modal/ability-bonus-modal.vue
<template>
    <div>
        <button class="uk-button uk-button-primary" type="button" uk-toggle="target: #ability-select-modal">
            Select ability bonus
        </button>
        <div id="ability-select-modal" uk-modal @beforehide="state.reset()">
            <div class="uk-modal-dialog uk-modal-body">
                <h2 class="uk-modal-title">Select an ability bonus</h2>
                <div class="uk-margin">
                    <select name="ability" id="ability" class="uk-select" v-model="state.ability.id">
                        <option value="">- Choose a ability -</option>
                        <option v-for="abilityOption in abilities" :value="abilityOption.id"
                                :disabled="selected.includes(abilityOption.id)">{{ abilityOption.name }}
                        </option>
                    </select>
                </div>
                <div class="uk-margin">
                    <label for="bonus">Bonus</label>
                    <input id="bonus" class="uk-input" type="number" min="1" v-model="state.ability.bonus">
                </div>
                <div class="uk-margin">
                    <label for="ability-optional">
                        <input id="ability-optional" class="uk-checkbox" type="checkbox"
                               v-model="state.ability.optional">
                        Optional
                    </label>
                </div>
                <div class="uk-margin">
                    <button class="uk-button uk-button-primary" type="button" @click.prevent="state.save">Select
                    </button>
                </div>
                <button class=" uk-modal-close-default uk-close-large" type="button" uk-close></button>
            </div>
        </div>
    </div>
</template>

<script>
import UIKit from "uikit";
import { useState } from "./ability-bonus-modal.state";

export default {
    name: "ability-bonus-modal",
    props: {
        selected: {
            type: Array,
            default: () => []
        }
    },
    setup(props, ctx) {
        const ui = {
            close: () => UIKit.modal('#ability-select-modal').hide()
        }
        const state = useState(ctx, ui)
        return {
            selected: props.selected,
            state
        }
    }
}
</script>

// resources/js/apps/admin/components/races/RaceForm/components/AbilityBonusModal/AbilityBonusModal.tsx
import InputSelect from "../../../../../../../components/layout/form/components/InputSelect";
import InputNumber from "../../../../../../../components/layout/form/components/InputNumber";
import InputBoolean from "../../../../../../../components/layout/form/components/InputBoolean";
import { useAbilityBonusModalState } from "./AbilityBonusModal.state";
import { FC } from "react";
import { AbilityBonusModalProps } from "./types";
import Modal from "../../../../../../../components/layout/Modal";

const AbilityBonusModal: FC<AbilityBonusModalProps> = ({ selected, onChange }) => {
  const { input, options, save, update } = useAbilityBonusModalState(selected, onChange)
  return (
    <div>
      <Modal id="ability-select-modal"
             trigger={<button className="uk-button uk-button-primary"
                              type="button">
               Select ability bonus
             </button>}>
        {input === null ? null :
          <>
            <InputSelect id="ability"
                         name="ability"
                         label=""
                         emptyLabel="Choose an ability"
                         options={options}
                         onChange={(value) => update('ability', value)}
                         initialValue={input.ability} />
            <InputNumber id="bonus"
                         name="bonus"
                         label="Bonus"
                         onChange={(value) => update('bonus', value)}
                         initialValue={input.bonus} />
            <InputBoolean onChange={(value) => update('optional', value)}
                          id="ability-optional"
                          name="ability-optional"
                          label="Optional"
                          initialValue={input.optional} />
            <div className="uk-margin">
              <button className="uk-button uk-button-primary" type="button" onClick={(e) => {
                e.preventDefault()
                save()
              }}>Select
              </button>
            </div>
          </>
        }
      </Modal>
    </div>
  )
}

export default AbilityBonusModal
