// resources/js/apps/campaign/components/Quests/QuestOverview/QuestOverview.tsx
import { Link } from "react-router-dom";
import PaginatedTable from "../../../../../components/layout/PaginatedTable";
import { useQuestOverviewState } from "./QuestOverview.state";
import { useQuestOverviewUI } from "./QuestOverview.ui";

const QuestOverview = () => {
  const { questRepository, destroy } = useQuestOverviewState()
  const ui = useQuestOverviewUI()

  return <div id="quests">
    <h1>Quests</h1>
    <div className="uk-section uk-section-default uk-padding-remove-top">
      {
        ui.can('create', 'quest') ?
          <Link className="uk-button uk-button-primary" to="/quests/create">
            <i className="fas fa-plus"></i> Add quest
          </Link> : null
      }
      {
        questRepository.quests !== null && questRepository.quests?.data?.length > 0 ?
          <PaginatedTable
            actions={ui.actions}
            columns={ui.columns}
            records={questRepository.quests}
            repository={{
              previous: questRepository.previous,
              page: questRepository.page,
              next: questRepository.next,
              load: questRepository.load
            }}
            onAction={(type: string, row) => {
              if (type === 'destroy') destroy(row.id)
            }}
          /> : <p className="uk-text-center">
            {questRepository.quests === null ? <i className="fas fa-sync fa-spin fa-2x"></i> :
              <span>Your quest log is empty!</span>}
          </p>
      }
    </div>
  </div>
}

export default QuestOverview

// resources/vue/campaign/components/quests/quest-overview/quest-overview.vue
<template>
    <div id="quests">
        <h1>Quests</h1>
        <div class="uk-section uk-section-default">
            <div class="uk-container padded">
                <router-link v-if="can('create', 'quest')"
                             class="uk-button uk-button-primary" :to="{name: 'quest-create'}">
                    <i class="fas fa-plus"></i> Add quest
                </router-link>
                <paginated-table v-if="quests != null && quests.data.length > 0"
                                 :actions="ui.actions"
                                 :columns="ui.columns"
                                 :store="store"
                                 :records="quests"
                                 @destroy="state.destroy"/>
                <p v-else class="uk-text-center">
                    <i v-if="quests == null" class="fas fa-sync fa-spin fa-2x"></i>
                    <span v-else>Your quest log is empty!</span>
                </p>
            </div>
        </div>
    </div>
</template>

<script>
import { useMainStore } from '@campaign/stores/main'
import { useQuestStore } from '@campaign/stores/quests'
import PaginatedTable from '@components/partial/paginated-table'
import { storeToRefs } from 'pinia/dist/pinia.esm-browser'
import { onMounted } from 'vue'
import { useQuestOverviewState } from './quest-overview.state'
import { ui } from './quest-overview.ui'

export default {
    name: 'QuestOverview',
    setup() {
        const store = useQuestStore()
        const { quests } = storeToRefs(store)
        const main = useMainStore()
        const state = useQuestOverviewState(store)

        onMounted(() => store.load())

        return { can: main.can, quests, state, store, ui }
    },
    components: { PaginatedTable }
}
</script>
